repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: check-ast
  - id: pretty-format-json
    args: [--autofix]
  - id: check-json
  - id: check-toml
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: fix-byte-order-marker
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-merge-conflict
  - id: debug-statements
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: sort-simple-yaml
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
  hooks:
  - id: python-use-type-annotations
  - id: python-no-eval
  - id: python-no-log-warn
- repo: https://github.com/pycqa/isort
  rev: 5.9.3
  hooks:
  - id: isort
    args:
      - --profile
      - black
      - --filter-files
- repo: https://github.com/psf/black
  rev: 21.7b0
  hooks:
  - id: black
- repo: https://github.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear]
- repo: https://github.com/asottile/pyupgrade
  rev: v2.23.3
  hooks:
  - id: pyupgrade
    args: [--py39-plus]
- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.1.0
  hooks:
  - id: add-trailing-comma
- repo: https://github.com/asottile/dead
  rev: v1.4.0
  hooks:
  - id: dead
    args: ['--exclude', 'configs/*']
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
- repo: https://github.com/guilatrova/tryceratops
  rev: v0.5.0
  hooks:
  - id: tryceratops
